config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :tracks
  resources :genres
  devise_for :users
  resources :users
  get 'profile' => 'users#profile', as: 'user_root'

  root 'home#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_attached_file :icon, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :users
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :desk, :icon)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
= form_for @genre do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@genre.errors.count, "error")} prohibited this genre from being saved:"
      %ul
        - @genre.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :desk
    = f.text_area :desk
  .field
    = f.label :icon
    = f.file_field :icon
  .actions
    = f.submit 'Save'

app/views/genres/edit.html.haml
%h1 Editing genre

= render 'form'

= link_to 'Show', @genre
\|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
%h1 Listing genres

%table
  %thead
    %tr
      %th Name
      %th Desk
      %th Icon
      %th
      %th
      %th

  %tbody
    - @genres.each do |genre|
      %tr
        %td= genre.name
        %td= genre.desk
        %td= genre.icon
        %td= link_to 'Show', genre
        %td= link_to 'Edit', edit_genre_path(genre)
        %td= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Genre', new_genre_path

app/views/genres/new.html.haml
%h1 New genre

= render 'form'

= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @genre.name
%p
  %b Desk:
  = @genre.desk
%p
  %b Icon:
  = image_tag @genre.icon.url, width: '300px'

= link_to 'Edit', edit_genre_path(@genre)
\|
= link_to 'Back', genres_path