config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :tracks
  resources :genres
  devise_for :users
  resources :users
  get 'profile' => 'users#profile', as: 'user_root'

  root 'home#index'

end

app/models/track.rb
class Track < ActiveRecord::Base
  has_attached_file :file
  validates_attachment_content_type :file,
    :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :playlists

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :author, :file)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.haml
= form_for @track do |f|
  - if @track.errors.any?
    #error_explanation
      %h2= "#{pluralize(@track.errors.count, "error")} prohibited this track from being saved:"
      %ul
        - @track.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :author
    = f.text_field :author
  .field
    = f.label :file
    = f.file_field :file
  .actions
    = f.submit 'Save'

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track
\|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
%h1 Listing tracks

%table
  %thead
    %tr
      %th Name
      %th Author
      %th File
      %th
      %th
      %th

  %tbody
    - @tracks.each do |track|
      %tr
        %td= track.name
        %td= track.author
        %td= track.file
        %td= link_to 'Show', track
        %td= link_to 'Edit', edit_track_path(track)
        %td= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Track', new_track_path

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

= link_to 'Back', tracks_path

app/views/tracks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @track.name
%p
  %b Author:
  = @track.author
%p
  %b File:
  = @track.file

= link_to 'Edit', edit_track_path(@track)
\|
= link_to 'Back', tracks_path