config/routes.rb
Rails.application.routes.draw do
  resources :playlists
  resources :tracks
  resources :genres
  devise_for :users
  resources :users
  get 'profile' => 'users#profile', as: 'user_root'

  root 'home#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  has_attached_file :icon, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.author = current_user
    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:name, :icon, :author_id, :status)
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.haml
= form_for @playlist do |f|
  - if @playlist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@playlist.errors.count, "error")} prohibited this playlist from being saved:"
      %ul
        - @playlist.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :icon
    %br
    = f.file_field :icon 
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/playlists/edit.html.haml
%h1 Editing playlist

= render 'form'

= link_to 'Show', @playlist
\|
= link_to 'Back', playlists_path

app/views/playlists/index.html.haml
%h1 Listing playlists

%table
  %thead
    %tr
      %th Name
      %th Icon
      %th Author
      %th Status
      %th
      %th
      %th

  %tbody
    - @playlists.each do |playlist|
      %tr
        %td= playlist.name
        %td= playlist.icon
        %td= playlist.author
        %td= playlist.status
        %td= link_to 'Show', playlist
        %td= link_to 'Edit', edit_playlist_path(playlist)
        %td= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Playlist', new_playlist_path

app/views/playlists/new.html.haml
%h1 New playlist

= render 'form'

= link_to 'Back', playlists_path

app/views/playlists/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @playlist.name
%p
  %b Icon:
  = image_tag @playlist.icon.url, width: '300px'
%p
  %b Author:
  = @playlist.author.login
%p
  %b Status:
  = @playlist.status

= link_to 'Edit', edit_playlist_path(@playlist)
\|
= link_to 'Back', playlists_path